<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ****************** -->
  <!--   LDS LiDAR Sensor -->
  <!-- ****************** -->
  
  <xacro:property name="lidar_mass" value="0.2"/>
  <xacro:property name="lidar_radius" value="0.035"/>
  <xacro:property name="lidar_height" value="0.08"/>

  <!-- LiDAR Link -->

  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${lidar_mass}"/>
      <xacro:solid_cylinder_inertia m="${lidar_mass}" r="${lidar_radius}" h="${lidar_height}"/>
    </inertial>
  </link>

  <!-- LiDAR Joint -->

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${base_size_z/2 + lidar_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- ****************** -->
  <!--   Gazebo Plugin    -->
  <!-- ****************** -->

  <gazebo reference="lidar_link">
    <sensor type="ray" name="lidar_sensor">
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14159</min_angle>
            <max_angle>3.14159</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>12.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_laser" filename="libgazebo_ros_laser.so">
        <ros>
          <namespace>/</namespace>
        </ros>
        <topicName>scan</topicName>
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>